// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type App struct {
	ID        int64
	UserID    int64
	Name      string
	AppID     int64
	AppKey    string
	Rate      int64
	Status    int64
	NotifyUrl string
	CreatedAt int64
	UpdatedAt int64
}

type BalanceLog struct {
	ID           int64
	UserID       int64
	Type         int64
	Amount       int64
	BalanceAfter int64
	RefID        int64
	Note         string
	CreatedAt    int64
}

type Order struct {
	ID              int64
	TradeNo         string
	OutTradeNo      string
	AppID           int64
	UserID          int64
	Channel         string
	Subject         string
	Money           int64
	Fee             int64
	Status          int64
	NotifyUrl       string
	ReturnUrl       string
	ClientIp        string
	Notified        int64
	NotifyAttempts  int64
	PaidAt          int64
	ExpiredAt       int64
	CreatedAt       int64
	UpdatedAt       int64
	UpstreamTradeNo string
	GoodsKey        string
	Quantity        int64
	UnitPrice       int64
	Payurl          string
	Qrcode          string
	BuyerContact    string
	QueryPwd        string
	Cards           string
}

type Session struct {
	Token     string
	UserID    int64
	ExpiresAt int64
	CreatedAt int64
	RotatedTo string
}

type Setting struct {
	Key   string
	Value string
}

type SettleRequest struct {
	ID        int64
	UserID    int64
	Amount    int64
	Fee       int64
	Account   string
	PayType   string
	Status    int64
	Remark    string
	CreatedAt int64
	HandledAt int64
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	Email        string
	Role         int64
	Status       int64
	Balance      int64
	CreatedAt    int64
	UpdatedAt    int64
}
