// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const addUserBalance = `-- name: AddUserBalance :one
UPDATE users SET balance = balance + ?1, updated_at = ?2
WHERE id = ?3
RETURNING balance
`

type AddUserBalanceParams struct {
	Delta int64
	Now   int64
	ID    int64
}

func (q *Queries) AddUserBalance(ctx context.Context, arg AddUserBalanceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addUserBalance, arg.Delta, arg.Now, arg.ID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const closeExpiredOrders = `-- name: CloseExpiredOrders :execrows
UPDATE orders SET status = 3, updated_at = ?1
WHERE status = 0 AND expired_at > 0 AND expired_at < ?1
`

func (q *Queries) CloseExpiredOrders(ctx context.Context, now int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeExpiredOrders, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countBalanceLogsByUser = `-- name: CountBalanceLogsByUser :one
SELECT COUNT(*) AS cnt FROM balance_logs WHERE user_id = ?1
`

func (q *Queries) CountBalanceLogsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBalanceLogsByUser, userID)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const countListUsers = `-- name: CountListUsers :one
SELECT COUNT(*) AS cnt
FROM users
WHERE (?1 IS NULL OR username LIKE '%' || ?1 || '%'
       OR email LIKE '%' || ?1 || '%')
`

func (q *Queries) CountListUsers(ctx context.Context, kw interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countListUsers, kw)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const countOrdersAll = `-- name: CountOrdersAll :one
SELECT COUNT(*) AS cnt
FROM orders o JOIN users u ON u.id = o.user_id
WHERE (?1 IS NULL OR o.status = ?1)
  AND (?2 IS NULL OR o.channel = ?2)
  AND (?3 IS NULL OR o.trade_no LIKE '%' || ?3 || '%'
       OR o.out_trade_no LIKE '%' || ?3 || '%' OR u.username LIKE '%' || ?3 || '%')
  AND (?4 IS NULL OR o.created_at >= ?4)
  AND (?5 IS NULL OR o.created_at < ?5)
`

type CountOrdersAllParams struct {
	Status  interface{}
	Channel interface{}
	Kw      interface{}
	TFrom   interface{}
	TTo     interface{}
}

func (q *Queries) CountOrdersAll(ctx context.Context, arg CountOrdersAllParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrdersAll,
		arg.Status,
		arg.Channel,
		arg.Kw,
		arg.TFrom,
		arg.TTo,
	)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const countOrdersByUser = `-- name: CountOrdersByUser :one
SELECT COUNT(*) AS cnt
FROM orders
WHERE user_id = ?1
  AND (?2 IS NULL OR status = ?2)
  AND (?3 IS NULL OR channel = ?3)
  AND (?4 IS NULL OR trade_no LIKE '%' || ?4 || '%'
       OR out_trade_no LIKE '%' || ?4 || '%')
  AND (?5 IS NULL OR created_at >= ?5)
  AND (?6 IS NULL OR created_at < ?6)
`

type CountOrdersByUserParams struct {
	UserID  int64
	Status  interface{}
	Channel interface{}
	Kw      interface{}
	TFrom   interface{}
	TTo     interface{}
}

func (q *Queries) CountOrdersByUser(ctx context.Context, arg CountOrdersByUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrdersByUser,
		arg.UserID,
		arg.Status,
		arg.Channel,
		arg.Kw,
		arg.TFrom,
		arg.TTo,
	)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const countSettlesAll = `-- name: CountSettlesAll :one
SELECT COUNT(*) AS cnt
FROM settle_requests
WHERE (?1 IS NULL OR status = ?1)
`

func (q *Queries) CountSettlesAll(ctx context.Context, status interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSettlesAll, status)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const countSettlesByUser = `-- name: CountSettlesByUser :one
SELECT COUNT(*) AS cnt FROM settle_requests WHERE user_id = ?1
`

func (q *Queries) CountSettlesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSettlesByUser, userID)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) AS cnt FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createApp = `-- name: CreateApp :one
INSERT INTO apps (user_id, name, app_id, app_key, rate, status, notify_url, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, 1,
        ?6, ?7, ?7)
RETURNING id
`

type CreateAppParams struct {
	UserID    int64
	Name      string
	AppID     int64
	AppKey    string
	Rate      int64
	NotifyUrl string
	Now       int64
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createApp,
		arg.UserID,
		arg.Name,
		arg.AppID,
		arg.AppKey,
		arg.Rate,
		arg.NotifyUrl,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createBalanceLog = `-- name: CreateBalanceLog :exec
INSERT INTO balance_logs (user_id, type, amount, balance_after, ref_id, note, created_at)
VALUES (?1, ?2, ?3, ?4,
        ?5, ?6, ?7)
`

type CreateBalanceLogParams struct {
	UserID       int64
	Type         int64
	Amount       int64
	BalanceAfter int64
	RefID        int64
	Note         string
	Now          int64
}

func (q *Queries) CreateBalanceLog(ctx context.Context, arg CreateBalanceLogParams) error {
	_, err := q.db.ExecContext(ctx, createBalanceLog,
		arg.UserID,
		arg.Type,
		arg.Amount,
		arg.BalanceAfter,
		arg.RefID,
		arg.Note,
		arg.Now,
	)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (trade_no, out_trade_no, app_id, user_id, channel, subject, money, fee,
                    status, notify_url, return_url, client_ip, expired_at, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4,
        ?5, ?6, ?7, ?8, 0,
        ?9, ?10, ?11, ?12,
        ?13, ?13)
RETURNING id
`

type CreateOrderParams struct {
	TradeNo    string
	OutTradeNo string
	AppID      int64
	UserID     int64
	Channel    string
	Subject    string
	Money      int64
	Fee        int64
	NotifyUrl  string
	ReturnUrl  string
	ClientIp   string
	ExpiredAt  int64
	Now        int64
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.TradeNo,
		arg.OutTradeNo,
		arg.AppID,
		arg.UserID,
		arg.Channel,
		arg.Subject,
		arg.Money,
		arg.Fee,
		arg.NotifyUrl,
		arg.ReturnUrl,
		arg.ClientIp,
		arg.ExpiredAt,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, user_id, expires_at, created_at)
VALUES (?1, ?2, ?3, ?4)
`

type CreateSessionParams struct {
	Token     string
	UserID    int64
	ExpiresAt int64
	Now       int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.Token,
		arg.UserID,
		arg.ExpiresAt,
		arg.Now,
	)
	return err
}

const createSettle = `-- name: CreateSettle :one
INSERT INTO settle_requests (user_id, amount, fee, account, pay_type, status, created_at)
VALUES (?1, ?2, ?3, ?4, ?5,
        0, ?6)
RETURNING id
`

type CreateSettleParams struct {
	UserID  int64
	Amount  int64
	Fee     int64
	Account string
	PayType string
	Now     int64
}

func (q *Queries) CreateSettle(ctx context.Context, arg CreateSettleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSettle,
		arg.UserID,
		arg.Amount,
		arg.Fee,
		arg.Account,
		arg.PayType,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, email, role, status, balance, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, 1, 0,
        ?5, ?5)
RETURNING id
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
	Email        string
	Role         int64
	Now          int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.Email,
		arg.Role,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteApp = `-- name: DeleteApp :execrows
DELETE FROM apps WHERE id = ?1 AND user_id = ?2
`

type DeleteAppParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteApp(ctx context.Context, arg DeleteAppParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteApp, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < ?1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, now int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, now)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = ?1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getApp = `-- name: GetApp :one
SELECT id, user_id, name, app_id, app_key, rate, status, notify_url, created_at, updated_at FROM apps WHERE id = ?1
`

func (q *Queries) GetApp(ctx context.Context, id int64) (App, error) {
	row := q.db.QueryRowContext(ctx, getApp, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AppID,
		&i.AppKey,
		&i.Rate,
		&i.Status,
		&i.NotifyUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppByAppId = `-- name: GetAppByAppId :one
SELECT id, user_id, name, app_id, app_key, rate, status, notify_url, created_at, updated_at FROM apps WHERE app_id = ?1
`

func (q *Queries) GetAppByAppId(ctx context.Context, appID int64) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppByAppId, appID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AppID,
		&i.AppKey,
		&i.Rate,
		&i.Status,
		&i.NotifyUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, trade_no, out_trade_no, app_id, user_id, channel, subject, money, fee, status, notify_url, return_url, client_ip, notified, notify_attempts, paid_at, expired_at, created_at, updated_at, upstream_trade_no, goods_key, quantity, unit_price, payurl, qrcode, buyer_contact, query_pwd, cards FROM orders WHERE id = ?1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TradeNo,
		&i.OutTradeNo,
		&i.AppID,
		&i.UserID,
		&i.Channel,
		&i.Subject,
		&i.Money,
		&i.Fee,
		&i.Status,
		&i.NotifyUrl,
		&i.ReturnUrl,
		&i.ClientIp,
		&i.Notified,
		&i.NotifyAttempts,
		&i.PaidAt,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpstreamTradeNo,
		&i.GoodsKey,
		&i.Quantity,
		&i.UnitPrice,
		&i.Payurl,
		&i.Qrcode,
		&i.BuyerContact,
		&i.QueryPwd,
		&i.Cards,
	)
	return i, err
}

const getOrderByTradeNo = `-- name: GetOrderByTradeNo :one
SELECT id, trade_no, out_trade_no, app_id, user_id, channel, subject, money, fee, status, notify_url, return_url, client_ip, notified, notify_attempts, paid_at, expired_at, created_at, updated_at, upstream_trade_no, goods_key, quantity, unit_price, payurl, qrcode, buyer_contact, query_pwd, cards FROM orders WHERE trade_no = ?1
`

func (q *Queries) GetOrderByTradeNo(ctx context.Context, tradeNo string) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByTradeNo, tradeNo)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TradeNo,
		&i.OutTradeNo,
		&i.AppID,
		&i.UserID,
		&i.Channel,
		&i.Subject,
		&i.Money,
		&i.Fee,
		&i.Status,
		&i.NotifyUrl,
		&i.ReturnUrl,
		&i.ClientIp,
		&i.Notified,
		&i.NotifyAttempts,
		&i.PaidAt,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpstreamTradeNo,
		&i.GoodsKey,
		&i.Quantity,
		&i.UnitPrice,
		&i.Payurl,
		&i.Qrcode,
		&i.BuyerContact,
		&i.QueryPwd,
		&i.Cards,
	)
	return i, err
}

const getOrderForOut = `-- name: GetOrderForOut :one
SELECT id, trade_no, out_trade_no, app_id, user_id, channel, subject, money, fee, status, notify_url, return_url, client_ip, notified, notify_attempts, paid_at, expired_at, created_at, updated_at, upstream_trade_no, goods_key, quantity, unit_price, payurl, qrcode, buyer_contact, query_pwd, cards FROM orders WHERE app_id = ?1 AND out_trade_no = ?2
`

type GetOrderForOutParams struct {
	AppID      int64
	OutTradeNo string
}

func (q *Queries) GetOrderForOut(ctx context.Context, arg GetOrderForOutParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderForOut, arg.AppID, arg.OutTradeNo)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TradeNo,
		&i.OutTradeNo,
		&i.AppID,
		&i.UserID,
		&i.Channel,
		&i.Subject,
		&i.Money,
		&i.Fee,
		&i.Status,
		&i.NotifyUrl,
		&i.ReturnUrl,
		&i.ClientIp,
		&i.Notified,
		&i.NotifyAttempts,
		&i.PaidAt,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpstreamTradeNo,
		&i.GoodsKey,
		&i.Quantity,
		&i.UnitPrice,
		&i.Payurl,
		&i.Qrcode,
		&i.BuyerContact,
		&i.QueryPwd,
		&i.Cards,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.username, u.password_hash, u.email, u.role, u.status, u.balance, u.created_at, u.updated_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token = ?1 AND s.expires_at > ?2 AND u.status = 1
`

type GetSessionUserParams struct {
	Token string
	Now   int64
}

func (q *Queries) GetSessionUser(ctx context.Context, arg GetSessionUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getSessionUser, arg.Token, arg.Now)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key = ?1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getSettle = `-- name: GetSettle :one
SELECT id, user_id, amount, fee, account, pay_type, status, remark, created_at, handled_at FROM settle_requests WHERE id = ?1
`

func (q *Queries) GetSettle(ctx context.Context, id int64) (SettleRequest, error) {
	row := q.db.QueryRowContext(ctx, getSettle, id)
	var i SettleRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Fee,
		&i.Account,
		&i.PayType,
		&i.Status,
		&i.Remark,
		&i.CreatedAt,
		&i.HandledAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, password_hash, email, role, status, balance, created_at, updated_at FROM users WHERE id = ?1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, email, role, status, balance, created_at, updated_at FROM users WHERE username = ?1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const globalTotals = `-- name: GlobalTotals :one
SELECT (SELECT COUNT(*) FROM users) AS user_cnt,
       (SELECT COUNT(*) FROM orders WHERE status = 1) AS paid_cnt,
       (SELECT COALESCE(SUM(money), 0) FROM orders WHERE status = 1) AS total_money,
       (SELECT COUNT(*) FROM settle_requests WHERE status = 0) AS pending_settle_cnt
`

type GlobalTotalsRow struct {
	UserCnt          int64
	PaidCnt          int64
	TotalMoney       interface{}
	PendingSettleCnt int64
}

func (q *Queries) GlobalTotals(ctx context.Context) (GlobalTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, globalTotals)
	var i GlobalTotalsRow
	err := row.Scan(
		&i.UserCnt,
		&i.PaidCnt,
		&i.TotalMoney,
		&i.PendingSettleCnt,
	)
	return i, err
}

const handleSettle = `-- name: HandleSettle :execrows
UPDATE settle_requests
SET status = ?1, remark = ?2, handled_at = ?3
WHERE id = ?4 AND status = 0
`

type HandleSettleParams struct {
	Status    int64
	Remark    string
	HandledAt int64
	ID        int64
}

func (q *Queries) HandleSettle(ctx context.Context, arg HandleSettleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, handleSettle,
		arg.Status,
		arg.Remark,
		arg.HandledAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const incNotifyAttempts = `-- name: IncNotifyAttempts :exec
UPDATE orders SET notify_attempts = notify_attempts + 1, updated_at = ?1
WHERE id = ?2
`

type IncNotifyAttemptsParams struct {
	Now int64
	ID  int64
}

func (q *Queries) IncNotifyAttempts(ctx context.Context, arg IncNotifyAttemptsParams) error {
	_, err := q.db.ExecContext(ctx, incNotifyAttempts, arg.Now, arg.ID)
	return err
}

const listAppsByUser = `-- name: ListAppsByUser :many
SELECT id, user_id, name, app_id, app_key, rate, status, notify_url, created_at, updated_at FROM apps WHERE user_id = ?1 ORDER BY id DESC
`

func (q *Queries) ListAppsByUser(ctx context.Context, userID int64) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []App
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.AppID,
			&i.AppKey,
			&i.Rate,
			&i.Status,
			&i.NotifyUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBalanceLogsByUser = `-- name: ListBalanceLogsByUser :many
SELECT id, user_id, type, amount, balance_after, ref_id, note, created_at FROM balance_logs WHERE user_id = ?1
ORDER BY id DESC LIMIT ?3 OFFSET ?2
`

type ListBalanceLogsByUserParams struct {
	UserID int64
	Off    int64
	Lim    int64
}

func (q *Queries) ListBalanceLogsByUser(ctx context.Context, arg ListBalanceLogsByUserParams) ([]BalanceLog, error) {
	rows, err := q.db.QueryContext(ctx, listBalanceLogsByUser, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BalanceLog
	for rows.Next() {
		var i BalanceLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Amount,
			&i.BalanceAfter,
			&i.RefID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersAll = `-- name: ListOrdersAll :many
SELECT o.id, o.trade_no, o.out_trade_no, o.app_id, o.user_id, o.channel, o.subject, o.money,
       o.fee, o.status, o.notify_url, o.return_url, o.notified, o.paid_at, o.expired_at,
       o.created_at, a.name AS app_name, a.app_id AS pid, u.username AS merchant
FROM orders o
JOIN apps a ON a.id = o.app_id
JOIN users u ON u.id = o.user_id
WHERE (?1 IS NULL OR o.status = ?1)
  AND (?2 IS NULL OR o.channel = ?2)
  AND (?3 IS NULL OR o.trade_no LIKE '%' || ?3 || '%'
       OR o.out_trade_no LIKE '%' || ?3 || '%' OR u.username LIKE '%' || ?3 || '%')
  AND (?4 IS NULL OR o.created_at >= ?4)
  AND (?5 IS NULL OR o.created_at < ?5)
ORDER BY o.id DESC
LIMIT ?7 OFFSET ?6
`

type ListOrdersAllParams struct {
	Status  interface{}
	Channel interface{}
	Kw      interface{}
	TFrom   interface{}
	TTo     interface{}
	Off     int64
	Lim     int64
}

type ListOrdersAllRow struct {
	ID         int64
	TradeNo    string
	OutTradeNo string
	AppID      int64
	UserID     int64
	Channel    string
	Subject    string
	Money      int64
	Fee        int64
	Status     int64
	NotifyUrl  string
	ReturnUrl  string
	Notified   int64
	PaidAt     int64
	ExpiredAt  int64
	CreatedAt  int64
	AppName    string
	Pid        int64
	Merchant   string
}

func (q *Queries) ListOrdersAll(ctx context.Context, arg ListOrdersAllParams) ([]ListOrdersAllRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersAll,
		arg.Status,
		arg.Channel,
		arg.Kw,
		arg.TFrom,
		arg.TTo,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersAllRow
	for rows.Next() {
		var i ListOrdersAllRow
		if err := rows.Scan(
			&i.ID,
			&i.TradeNo,
			&i.OutTradeNo,
			&i.AppID,
			&i.UserID,
			&i.Channel,
			&i.Subject,
			&i.Money,
			&i.Fee,
			&i.Status,
			&i.NotifyUrl,
			&i.ReturnUrl,
			&i.Notified,
			&i.PaidAt,
			&i.ExpiredAt,
			&i.CreatedAt,
			&i.AppName,
			&i.Pid,
			&i.Merchant,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT o.id, o.trade_no, o.out_trade_no, o.app_id, o.user_id, o.channel, o.subject, o.money,
       o.fee, o.status, o.notify_url, o.return_url, o.notified, o.notify_attempts, o.paid_at, o.expired_at,
       o.created_at, a.name AS app_name, a.app_id AS pid
FROM orders o JOIN apps a ON a.id = o.app_id
WHERE o.user_id = ?1
  AND (?2 IS NULL OR o.status = ?2)
  AND (?3 IS NULL OR o.channel = ?3)
  AND (?4 IS NULL OR o.trade_no LIKE '%' || ?4 || '%'
       OR o.out_trade_no LIKE '%' || ?4 || '%')
  AND (?5 IS NULL OR o.created_at >= ?5)
  AND (?6 IS NULL OR o.created_at < ?6)
ORDER BY o.id DESC
LIMIT ?8 OFFSET ?7
`

type ListOrdersByUserParams struct {
	UserID  int64
	Status  interface{}
	Channel interface{}
	Kw      interface{}
	TFrom   interface{}
	TTo     interface{}
	Off     int64
	Lim     int64
}

type ListOrdersByUserRow struct {
	ID             int64
	TradeNo        string
	OutTradeNo     string
	AppID          int64
	UserID         int64
	Channel        string
	Subject        string
	Money          int64
	Fee            int64
	Status         int64
	NotifyUrl      string
	ReturnUrl      string
	Notified       int64
	NotifyAttempts int64
	PaidAt         int64
	ExpiredAt      int64
	CreatedAt      int64
	AppName        string
	Pid            int64
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]ListOrdersByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByUser,
		arg.UserID,
		arg.Status,
		arg.Channel,
		arg.Kw,
		arg.TFrom,
		arg.TTo,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersByUserRow
	for rows.Next() {
		var i ListOrdersByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TradeNo,
			&i.OutTradeNo,
			&i.AppID,
			&i.UserID,
			&i.Channel,
			&i.Subject,
			&i.Money,
			&i.Fee,
			&i.Status,
			&i.NotifyUrl,
			&i.ReturnUrl,
			&i.Notified,
			&i.NotifyAttempts,
			&i.PaidAt,
			&i.ExpiredAt,
			&i.CreatedAt,
			&i.AppName,
			&i.Pid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingUpstreamOrders = `-- name: ListPendingUpstreamOrders :many
SELECT id, trade_no, out_trade_no, app_id, user_id, channel, subject, money, fee, status, notify_url, return_url, client_ip, notified, notify_attempts, paid_at, expired_at, created_at, updated_at, upstream_trade_no, goods_key, quantity, unit_price, payurl, qrcode, buyer_contact, query_pwd, cards FROM orders
WHERE status IN (0, 3) AND upstream_trade_no <> '' AND created_at >= ?1
ORDER BY id ASC
LIMIT ?2
`

type ListPendingUpstreamOrdersParams struct {
	MinCreatedAt int64
	Lim          int64
}

func (q *Queries) ListPendingUpstreamOrders(ctx context.Context, arg ListPendingUpstreamOrdersParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listPendingUpstreamOrders, arg.MinCreatedAt, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.TradeNo,
			&i.OutTradeNo,
			&i.AppID,
			&i.UserID,
			&i.Channel,
			&i.Subject,
			&i.Money,
			&i.Fee,
			&i.Status,
			&i.NotifyUrl,
			&i.ReturnUrl,
			&i.ClientIp,
			&i.Notified,
			&i.NotifyAttempts,
			&i.PaidAt,
			&i.ExpiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpstreamTradeNo,
			&i.GoodsKey,
			&i.Quantity,
			&i.UnitPrice,
			&i.Payurl,
			&i.Qrcode,
			&i.BuyerContact,
			&i.QueryPwd,
			&i.Cards,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentOrdersAll = `-- name: ListRecentOrdersAll :many
SELECT o.id, o.trade_no, o.out_trade_no, o.app_id, o.user_id, o.channel, o.subject, o.money,
       o.fee, o.status, o.notify_url, o.return_url, o.notified, o.paid_at, o.expired_at,
       o.created_at, a.name AS app_name, a.app_id AS pid, u.username AS merchant
FROM orders o
JOIN apps a ON a.id = o.app_id
JOIN users u ON u.id = o.user_id
ORDER BY o.id DESC
LIMIT ?1
`

type ListRecentOrdersAllRow struct {
	ID         int64
	TradeNo    string
	OutTradeNo string
	AppID      int64
	UserID     int64
	Channel    string
	Subject    string
	Money      int64
	Fee        int64
	Status     int64
	NotifyUrl  string
	ReturnUrl  string
	Notified   int64
	PaidAt     int64
	ExpiredAt  int64
	CreatedAt  int64
	AppName    string
	Pid        int64
	Merchant   string
}

func (q *Queries) ListRecentOrdersAll(ctx context.Context, lim int64) ([]ListRecentOrdersAllRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentOrdersAll, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentOrdersAllRow
	for rows.Next() {
		var i ListRecentOrdersAllRow
		if err := rows.Scan(
			&i.ID,
			&i.TradeNo,
			&i.OutTradeNo,
			&i.AppID,
			&i.UserID,
			&i.Channel,
			&i.Subject,
			&i.Money,
			&i.Fee,
			&i.Status,
			&i.NotifyUrl,
			&i.ReturnUrl,
			&i.Notified,
			&i.PaidAt,
			&i.ExpiredAt,
			&i.CreatedAt,
			&i.AppName,
			&i.Pid,
			&i.Merchant,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentOrdersByUser = `-- name: ListRecentOrdersByUser :many
SELECT o.id, o.trade_no, o.out_trade_no, o.app_id, o.user_id, o.channel, o.subject, o.money,
       o.fee, o.status, o.notify_url, o.return_url, o.notified, o.paid_at, o.expired_at,
       o.created_at, a.name AS app_name, a.app_id AS pid
FROM orders o JOIN apps a ON a.id = o.app_id
WHERE o.user_id = ?1
ORDER BY o.id DESC
LIMIT ?2
`

type ListRecentOrdersByUserParams struct {
	UserID int64
	Lim    int64
}

type ListRecentOrdersByUserRow struct {
	ID         int64
	TradeNo    string
	OutTradeNo string
	AppID      int64
	UserID     int64
	Channel    string
	Subject    string
	Money      int64
	Fee        int64
	Status     int64
	NotifyUrl  string
	ReturnUrl  string
	Notified   int64
	PaidAt     int64
	ExpiredAt  int64
	CreatedAt  int64
	AppName    string
	Pid        int64
}

func (q *Queries) ListRecentOrdersByUser(ctx context.Context, arg ListRecentOrdersByUserParams) ([]ListRecentOrdersByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentOrdersByUser, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentOrdersByUserRow
	for rows.Next() {
		var i ListRecentOrdersByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TradeNo,
			&i.OutTradeNo,
			&i.AppID,
			&i.UserID,
			&i.Channel,
			&i.Subject,
			&i.Money,
			&i.Fee,
			&i.Status,
			&i.NotifyUrl,
			&i.ReturnUrl,
			&i.Notified,
			&i.PaidAt,
			&i.ExpiredAt,
			&i.CreatedAt,
			&i.AppName,
			&i.Pid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettings = `-- name: ListSettings :many
SELECT key, value FROM settings
`

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlesAll = `-- name: ListSettlesAll :many
SELECT s.id, s.user_id, s.amount, s.fee, s.account, s.pay_type, s.status, s.remark,
       s.created_at, s.handled_at, u.username AS merchant
FROM settle_requests s JOIN users u ON u.id = s.user_id
WHERE (?1 IS NULL OR s.status = ?1)
ORDER BY s.id DESC LIMIT ?3 OFFSET ?2
`

type ListSettlesAllParams struct {
	Status interface{}
	Off    int64
	Lim    int64
}

type ListSettlesAllRow struct {
	ID        int64
	UserID    int64
	Amount    int64
	Fee       int64
	Account   string
	PayType   string
	Status    int64
	Remark    string
	CreatedAt int64
	HandledAt int64
	Merchant  string
}

func (q *Queries) ListSettlesAll(ctx context.Context, arg ListSettlesAllParams) ([]ListSettlesAllRow, error) {
	rows, err := q.db.QueryContext(ctx, listSettlesAll, arg.Status, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSettlesAllRow
	for rows.Next() {
		var i ListSettlesAllRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Fee,
			&i.Account,
			&i.PayType,
			&i.Status,
			&i.Remark,
			&i.CreatedAt,
			&i.HandledAt,
			&i.Merchant,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlesByUser = `-- name: ListSettlesByUser :many
SELECT id, user_id, amount, fee, account, pay_type, status, remark, created_at, handled_at FROM settle_requests WHERE user_id = ?1
ORDER BY id DESC LIMIT ?3 OFFSET ?2
`

type ListSettlesByUserParams struct {
	UserID int64
	Off    int64
	Lim    int64
}

func (q *Queries) ListSettlesByUser(ctx context.Context, arg ListSettlesByUserParams) ([]SettleRequest, error) {
	rows, err := q.db.QueryContext(ctx, listSettlesByUser, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SettleRequest
	for rows.Next() {
		var i SettleRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Fee,
			&i.Account,
			&i.PayType,
			&i.Status,
			&i.Remark,
			&i.CreatedAt,
			&i.HandledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnnotifiedPaidOrders = `-- name: ListUnnotifiedPaidOrders :many
SELECT trade_no FROM orders
WHERE status = 1 AND notified = 0 AND notify_url != '' AND notify_attempts < 5
ORDER BY id DESC LIMIT ?1
`

func (q *Queries) ListUnnotifiedPaidOrders(ctx context.Context, lim int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUnnotifiedPaidOrders, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var trade_no string
		if err := rows.Scan(&trade_no); err != nil {
			return nil, err
		}
		items = append(items, trade_no)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, role, status, balance, created_at
FROM users
WHERE (?1 IS NULL OR username LIKE '%' || ?1 || '%'
       OR email LIKE '%' || ?1 || '%')
ORDER BY id DESC
LIMIT ?3 OFFSET ?2
`

type ListUsersParams struct {
	Kw  interface{}
	Off int64
	Lim int64
}

type ListUsersRow struct {
	ID        int64
	Username  string
	Email     string
	Role      int64
	Status    int64
	Balance   int64
	CreatedAt int64
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Kw, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.Balance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderNotified = `-- name: MarkOrderNotified :exec
UPDATE orders SET notified = 1, notify_attempts = ?1, updated_at = ?2
WHERE id = ?3
`

type MarkOrderNotifiedParams struct {
	Attempts int64
	Now      int64
	ID       int64
}

func (q *Queries) MarkOrderNotified(ctx context.Context, arg MarkOrderNotifiedParams) error {
	_, err := q.db.ExecContext(ctx, markOrderNotified, arg.Attempts, arg.Now, arg.ID)
	return err
}

const markOrderPaid = `-- name: MarkOrderPaid :execrows
UPDATE orders SET status = 1, paid_at = ?1, updated_at = ?2
WHERE id = ?3 AND status = 0
`

type MarkOrderPaidParams struct {
	PaidAt int64
	Now    int64
	ID     int64
}

func (q *Queries) MarkOrderPaid(ctx context.Context, arg MarkOrderPaidParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOrderPaid, arg.PaidAt, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markOrderRefunded = `-- name: MarkOrderRefunded :execrows
UPDATE orders SET status = 2, updated_at = ?1
WHERE id = ?2 AND status = 1
`

type MarkOrderRefundedParams struct {
	Now int64
	ID  int64
}

func (q *Queries) MarkOrderRefunded(ctx context.Context, arg MarkOrderRefundedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOrderRefunded, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markUpstreamOrderPaid = `-- name: MarkUpstreamOrderPaid :execrows
UPDATE orders SET status = 1, paid_at = ?1, updated_at = ?2
WHERE id = ?3 AND status IN (0, 3) AND upstream_trade_no <> ''
`

type MarkUpstreamOrderPaidParams struct {
	PaidAt int64
	Now    int64
	ID     int64
}

func (q *Queries) MarkUpstreamOrderPaid(ctx context.Context, arg MarkUpstreamOrderPaidParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markUpstreamOrderPaid, arg.PaidAt, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const maxAppId = `-- name: MaxAppId :one
SELECT COALESCE(MAX(app_id), 1000) AS max_id FROM apps
`

func (q *Queries) MaxAppId(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxAppId)
	var max_id interface{}
	err := row.Scan(&max_id)
	return max_id, err
}

const orderStatsAll = `-- name: OrderStatsAll :one
SELECT COUNT(*) AS cnt, COALESCE(SUM(money), 0) AS total_money, COALESCE(SUM(fee), 0) AS total_fee
FROM orders
WHERE status = 1 AND created_at >= ?1 AND created_at < ?2
`

type OrderStatsAllParams struct {
	TFrom int64
	TTo   int64
}

type OrderStatsAllRow struct {
	Cnt        int64
	TotalMoney interface{}
	TotalFee   interface{}
}

func (q *Queries) OrderStatsAll(ctx context.Context, arg OrderStatsAllParams) (OrderStatsAllRow, error) {
	row := q.db.QueryRowContext(ctx, orderStatsAll, arg.TFrom, arg.TTo)
	var i OrderStatsAllRow
	err := row.Scan(&i.Cnt, &i.TotalMoney, &i.TotalFee)
	return i, err
}

const orderStatsByUser = `-- name: OrderStatsByUser :one
SELECT COUNT(*) AS cnt, COALESCE(SUM(money), 0) AS total_money, COALESCE(SUM(fee), 0) AS total_fee
FROM orders
WHERE user_id = ?1 AND status = 1
  AND created_at >= ?2 AND created_at < ?3
`

type OrderStatsByUserParams struct {
	UserID int64
	TFrom  int64
	TTo    int64
}

type OrderStatsByUserRow struct {
	Cnt        int64
	TotalMoney interface{}
	TotalFee   interface{}
}

func (q *Queries) OrderStatsByUser(ctx context.Context, arg OrderStatsByUserParams) (OrderStatsByUserRow, error) {
	row := q.db.QueryRowContext(ctx, orderStatsByUser, arg.UserID, arg.TFrom, arg.TTo)
	var i OrderStatsByUserRow
	err := row.Scan(&i.Cnt, &i.TotalMoney, &i.TotalFee)
	return i, err
}

const resetAppKey = `-- name: ResetAppKey :exec
UPDATE apps SET app_key = ?1, updated_at = ?2 WHERE id = ?3
`

type ResetAppKeyParams struct {
	AppKey string
	Now    int64
	ID     int64
}

func (q *Queries) ResetAppKey(ctx context.Context, arg ResetAppKeyParams) error {
	_, err := q.db.ExecContext(ctx, resetAppKey, arg.AppKey, arg.Now, arg.ID)
	return err
}

const resetOrderNotify = `-- name: ResetOrderNotify :exec
UPDATE orders SET notified = 0, notify_attempts = 0, updated_at = ?1
WHERE id = ?2
`

type ResetOrderNotifyParams struct {
	Now int64
	ID  int64
}

func (q *Queries) ResetOrderNotify(ctx context.Context, arg ResetOrderNotifyParams) error {
	_, err := q.db.ExecContext(ctx, resetOrderNotify, arg.Now, arg.ID)
	return err
}

const setOrderCards = `-- name: SetOrderCards :exec
UPDATE orders SET cards = ?1, updated_at = ?2 WHERE id = ?3
`

type SetOrderCardsParams struct {
	Cards string
	Now   int64
	ID    int64
}

func (q *Queries) SetOrderCards(ctx context.Context, arg SetOrderCardsParams) error {
	_, err := q.db.ExecContext(ctx, setOrderCards, arg.Cards, arg.Now, arg.ID)
	return err
}

const setOrderQrcode = `-- name: SetOrderQrcode :exec
UPDATE orders SET qrcode = ?1, updated_at = ?2
WHERE id = ?3
`

type SetOrderQrcodeParams struct {
	Qrcode string
	Now    int64
	ID     int64
}

func (q *Queries) SetOrderQrcode(ctx context.Context, arg SetOrderQrcodeParams) error {
	_, err := q.db.ExecContext(ctx, setOrderQrcode, arg.Qrcode, arg.Now, arg.ID)
	return err
}

const setOrderStatus = `-- name: SetOrderStatus :execrows
UPDATE orders SET status = ?1, updated_at = ?2
WHERE id = ?3
`

type SetOrderStatusParams struct {
	Status int64
	Now    int64
	ID     int64
}

func (q *Queries) SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setOrderStatus, arg.Status, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setOrderUpstream = `-- name: SetOrderUpstream :exec
UPDATE orders SET upstream_trade_no = ?1, goods_key = ?2, quantity = ?3,
       unit_price = ?4, payurl = ?5, qrcode = ?6, buyer_contact = ?7,
       query_pwd = ?8, updated_at = ?9
WHERE id = ?10
`

type SetOrderUpstreamParams struct {
	UpTradeNo    string
	GoodsKey     string
	Quantity     int64
	UnitPrice    int64
	Payurl       string
	Qrcode       string
	BuyerContact string
	QueryPwd     string
	Now          int64
	ID           int64
}

func (q *Queries) SetOrderUpstream(ctx context.Context, arg SetOrderUpstreamParams) error {
	_, err := q.db.ExecContext(ctx, setOrderUpstream,
		arg.UpTradeNo,
		arg.GoodsKey,
		arg.Quantity,
		arg.UnitPrice,
		arg.Payurl,
		arg.Qrcode,
		arg.BuyerContact,
		arg.QueryPwd,
		arg.Now,
		arg.ID,
	)
	return err
}

const updateApp = `-- name: UpdateApp :execrows
UPDATE apps
SET name = ?1, notify_url = ?2, rate = ?3, status = ?4, updated_at = ?5
WHERE id = ?6 AND user_id = ?7
`

type UpdateAppParams struct {
	Name      string
	NotifyUrl string
	Rate      int64
	Status    int64
	Now       int64
	ID        int64
	UserID    int64
}

func (q *Queries) UpdateApp(ctx context.Context, arg UpdateAppParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateApp,
		arg.Name,
		arg.NotifyUrl,
		arg.Rate,
		arg.Status,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password_hash = ?1, updated_at = ?2
WHERE id = ?3
`

type UpdatePasswordParams struct {
	PasswordHash string
	Now          int64
	ID           int64
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.PasswordHash, arg.Now, arg.ID)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :execrows
UPDATE users SET status = ?1, updated_at = ?2 WHERE id = ?3
`

type UpdateUserStatusParams struct {
	Status int64
	Now    int64
	ID     int64
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserStatus, arg.Status, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (key, value) VALUES (?1, ?2)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type UpsertSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}
